---
# Source: stackgres-cluster/charts/minio/templates/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: stackgres-cluster-minio
  namespace: database
type: Opaque
data:
  accesskey: "QUtJQUlPU0ZPRE5ON0VYQU1QTEU="
  secretkey: "d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ=="

---
# Source: stackgres-cluster/charts/minio/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: stackgres-cluster-minio
  namespace: database
data:
  initialize: |-
    #!/bin/sh
    set -e ; # Have script exit in the event of a failed command.
    
    # connectToMinio
    # Use a check-sleep-check loop to wait for Minio service to be available
    connectToMinio() {
      SCHEME=$1
      ATTEMPTS=0 ; LIMIT=29 ; # Allow 30 attempts
      set -e ; # fail if we can't read the keys.
      ACCESS=$(cat /config/accesskey) ; SECRET=$(cat /config/secretkey) ;
      set +e ; # The connections to minio are allowed to fail.
      echo "Connecting to Minio server: $SCHEME://$MINIO_ENDPOINT:$MINIO_PORT" ;
      MC_COMMAND="mc config host add myminio $SCHEME://$MINIO_ENDPOINT:$MINIO_PORT $ACCESS $SECRET" ;
      $MC_COMMAND ;
      STATUS=$? ;
      until [ $STATUS = 0 ]
      do
        ATTEMPTS=`expr $ATTEMPTS + 1` ;
        echo \"Failed attempts: $ATTEMPTS\" ;
        if [ $ATTEMPTS -gt $LIMIT ]; then
          exit 1 ;
        fi ;
        sleep 2 ; # 1 second intervals between attempts
        $MC_COMMAND ;
        STATUS=$? ;
      done ;
      set -e ; # reset `e` as active
      return 0
    }
    
    # checkBucketExists ($bucket)
    # Check if the bucket exists, by using the exit code of `mc ls`
    checkBucketExists() {
      BUCKET=$1
      CMD=$(/usr/bin/mc ls myminio/$BUCKET > /dev/null 2>&1)
      return $?
    }
    
    # createBucket ($bucket, $policy, $purge)
    # Ensure bucket exists, purging if asked to
    createBucket() {
      BUCKET=$1
      POLICY=$2
      PURGE=$3
    
      # Purge the bucket, if set & exists
      # Since PURGE is user input, check explicitly for `true`
      if [ $PURGE = true ]; then
        if checkBucketExists $BUCKET ; then
          echo "Purging bucket '$BUCKET'."
          set +e ; # don't exit if this fails
          /usr/bin/mc rm -r --force myminio/$BUCKET
          set -e ; # reset `e` as active
        else
          echo "Bucket '$BUCKET' does not exist, skipping purge."
        fi
      fi
    
      # Create the bucket if it does not exist
      if ! checkBucketExists $BUCKET ; then
        echo "Creating bucket '$BUCKET'"
        /usr/bin/mc mb myminio/$BUCKET
      else
        echo "Bucket '$BUCKET' already exists."
      fi
    
      # At this point, the bucket should exist, skip checking for existence
      # Set policy on the bucket
      echo "Setting policy of bucket '$BUCKET' to '$POLICY'."
      /usr/bin/mc policy set $POLICY myminio/$BUCKET
    }
    
    # Try connecting to Minio instance
    scheme=http
    connectToMinio $scheme
    # Create the buckets
    createBucket stackgres none true
    

---
# Source: stackgres-cluster/charts/minio/templates/pvc.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stackgres-cluster-minio
  namespace: database
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"

---
# Source: stackgres-cluster/charts/minio/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "stackgres-cluster-minio"
  namespace: database
---
# Source: stackgres-cluster/charts/minio/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: stackgres-cluster-minio
  namespace: database
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio
    release: stackgres-cluster

---
# Source: stackgres-cluster/charts/minio/templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackgres-cluster-minio
  namespace: database
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: minio
      release: stackgres-cluster
  template:
    metadata:
      name: stackgres-cluster-minio
      labels:
        app: minio
        release: stackgres-cluster
      annotations:
        checksum/secrets: c3f2588138aeac08190cfadcdfc6fc557b35cd44a6884d3e31b84261a3dd115a
        checksum/config: e4731ef2cd17ceeda8febdca61e93c44ac0a6514e36139a21ab1dc60b142cc79
    spec:
      serviceAccountName: "stackgres-cluster-minio"
      containers:
        - name: minio
          image: "minio/minio:RELEASE.2019-08-07T01-59-21Z"
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh", 
          "-ce", 
          "/usr/bin/docker-entrypoint.sh minio -C /root/.minio/ server /export" ]
          volumeMounts:
            - name: export
              mountPath: /export
            - name: minio-config-dir
              mountPath: /root/.minio/
          ports:
            - name: service
              containerPort: 9000
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: stackgres-cluster-minio
                  key: accesskey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stackgres-cluster-minio
                  key: secretkey
            - name: MINIO_BROWSER
              value: "on"
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: service
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: service
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            
      volumes:
        - name: export
          persistentVolumeClaim:
            claimName: stackgres-cluster-minio
        - name: minio-user
          secret:
            secretName: stackgres-cluster-minio
        - name: minio-config-dir
          emptyDir: {}

---
# Source: stackgres-cluster/charts/minio/templates/post-install-create-bucket-job.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: stackgres-cluster-minio-make-bucket-job
  namespace: database
spec:
  template:
    metadata:
      labels:
        app: minio
        release: stackgres-cluster
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: minio-configuration
          projected:
            sources:
            - configMap:
                name: stackgres-cluster-minio
            - secret:
                name: stackgres-cluster-minio
      containers:
      - name: minio-mc
        image: "minio/mc:RELEASE.2019-08-07T23-14-43Z"
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "/config/initialize"]
        env:
          - name: MINIO_ENDPOINT
            value: stackgres-cluster-minio
          - name: MINIO_PORT
            value: "9000"
        volumeMounts:
          - name: minio-configuration
            mountPath: /config
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          

